course/urls.py
from django.urls import path
from .views import CourseListView, CourseFormView, CourseDetailView, DocumentFormView
from . import views
app_name = 'course'
urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('form/', CourseFormView.as_view(), name='form'),
    # path('notes/', views.UploadDocumentFormView, name='upload'),
    path('<str:course_name>/', CourseDetailView.as_view(), name='detail'),
    path('<str:course_name>/notes/', views.DocumentFormView, name='upload'), # goes to the file list for class
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name="schedule/home.html")),

    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),

    path('course/', include('course.urls')),
    path('schedule/', include('schedule.urls')),

] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # need this line to go to media for files

course/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_out
from django.contrib import messages
import os


class Course(models.Model):
    course_name = models.CharField(max_length=200, default="class")
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.course_name

def upload_path(instance, filename) :
    # dynamically create an upload path used in AWS S3
    return instance.course.course_name + '/ ' + filename

class Document(models.Model):
    # dynamically change upload path
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    docfile = models.FileField(upload_to=upload_path)

    def filename(self): # remove a full path from the filename
        return os.path.basename(self.docfile.name)
    def __str__(self): # use the formatted pathname for its string representation
        return self.filename()

# when a user logs out, display a confirmation message
def logout_task(sender, user, request, **kwargs):
    messages.add_message(
        request,
        messages.INFO,
        f"You are successfully logged out.",
    )
user_logged_out.connect(logout_task)

course/forms.py
from django import forms
from .models import Document

class CourseForm(forms.Form):
    course_name = forms.CharField(max_length=200)

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['docfile']

course/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .forms import CourseForm, DocumentForm
from .models import Course, Document

from schedule.models import Assignment
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch') # have to do this for classes
class CourseListView(generic.ListView):
    template_name = 'course/course_list.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        user_info = self.request.user
        cur_user = User.objects.get(username=user_info.username, email=user_info.email)
        return cur_user.course_set.all()

@method_decorator(login_required, name='dispatch') # have to do this for classes
class CourseDetailView(generic.DetailView):
    model = Course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c = get_object_or_404(Course, course_name=self.kwargs.get("course_name"))
        context['documents'] = c.document_set.all()
        context['assignments'] = Assignment.objects.filter(user_id=self.request.user.id).filter(course=c)
        return context

    def get_object(self, queryset=None):
        return get_object_or_404(Course, course_name=self.kwargs.get("course_name"))


@method_decorator(login_required, name='dispatch') # have to do this for classes
class CourseFormView(generic.FormView):
    template_name = 'course/course_form.html'
    form_class = CourseForm

    def get_context_data(self, **kwargs):
        user_info = self.request.user
        cur_user = User.objects.get(username=user_info.username, email=user_info.email)
        all_current_courses = Course.objects.all()
        context = super().get_context_data(**kwargs)
        context['course_list'] = all_current_courses
        return context

    def form_valid(self, form):
        user_info = self.request.user
        course_name = form.cleaned_data.get('course_name').upper()
        cur_user = User.objects.get(username=user_info.username, email=user_info.email)

        course, created = Course.objects.get_or_create(course_name=course_name)
        course.users.add(cur_user)
        return HttpResponseRedirect(reverse('course:list'))


@login_required
def DocumentFormView(request, course_name):
    message = 'Upload Notes!'
    course = Course.objects.get(course_name=course_name)
    if request.method == 'POST': # if the request is POST
        form = DocumentForm(request.POST, request.FILES) # creates a document
        if form.is_valid():
            doc = form.save(commit=False)
            doc.course = course
            doc.save()
            return HttpResponseRedirect(reverse('course:detail', kwargs={'course_name': course_name}))
        else:
            message = 'invalid form:'
    else:
        form = DocumentForm()  # A empty, unbound form, if they don't post

    # Render list page with the documents and the form
    context = {'course_name': course_name, 'form': form, 'message': message}
    return render(request, 'course/course_document_form.html', context)

course/templates/course/course_detail.html
{% extends 'schedule/layout.html' %}


{% block content %}

<div class="bg3"></div>
  <section>
    <div class="container-fluid p-3 bg-dark bg-gradient text-white text-center">
      <h1>{{ course.course_name }}</h1>
    </div>
    <div class="p-5">
      <div class="mt-5">
        {% if user in course.users.all %}
        <a href="{% url 'course:upload' course_name=course.course_name %}"
           class="btn btn-primary"><i class="bi bi-file-earmark-arrow-up-fill"></i>
          Upload a new document
        </a>
        {% else %}
        <!-- I'm trying to make this join course button that enrolls a user into a course
        when they click it. DID IT -->
        <form action="{% url 'course:form' %}" method="post">
          {% csrf_token %}
          <input type="hidden" value="{{ course.course_name }}" name="course_name">
          <input type="submit" value="Join course" class="btn btn-primary" >
        </form>
        {% endif %}
        <a href="{% url 'course:list' %}" class="btn btn-warning"><i class="bi bi-arrow-left-square-fill"></i> Return to list</a>
      </div>

      <h4>Assignments</h4>
      {% if assignments %}
        <ul class="list-group list-group-flush mx-5 my-3 w-50">
          {% for item in assignments %}
            <li class="list-group-item">{{ item.title }} {{ item.due_date }}</li>
          {% endfor %}

        </ul>
      {% else %}
        <p>No assignments for this course</p>
      {% endif %}
      <h4>Students</h4>
      {% if course.users %}
        <ul class="list-group list-group-flush mx-5 my-3 w-50">
          {% for user in course.users.all %}
            <li class="list-group-item">{{ user.username }}</li>
          {% endfor %}
        </ul>
      {% else %}
        <p>no user signed up for this course</p>
      {% endif %}
      <h4 class="">Documents</h4>
      {% if documents %}
        <ul class="list-group mx-5 my-3 w-50">
          {% for doc in documents %}
            <li class="list-group-item"><a href="{{ doc.docfile.url }}" target="_blank" rel="noopener noreferrer">{{ doc.filename }}</a></li>
          {% endfor %}
        </ul>
      {% else %}
        <p>No document in this course</p>
      {% endif %}

    </div>
  </section>
{% endblock %}

course/templates/course/course_document_form.html
{% extends 'schedule/layout.html' %}

{% block content %}
  <!-- Upload form. Note enctype attribute! -->
  <form action="{% url 'course:upload' course_name=course_name %}"
        method="post" enctype="multipart/form-data" 
                      class="mt-5 text-center">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-danger">Upload</button>
  </form>
{% endblock %}

course/templates/course/course_form.html
{% extends 'schedule/layout.html' %}

{% block content %}

  <section>
    <div class="container-fluid p-3 bg-dark text-white text-center">
      <h1>Sign up for a course</h1>
      <p>Search for existing courses or create a new one</p>
    </div>

    <div class="bg2"></div>

    <form action="{% url 'course:form' %}" method="post" class="mt-3 text-center search">
      {% csrf_token %}
      {{ form.as_p }}

        {% if error_message %}
          <div class="alert alert-danger">
            <strong>Warning!</strong> Please fill out the text boxes.
          </div>
        {% endif %}

      <button type="submit" class="btn btn-primary text-white" >
        Create
      </button>
    </form>
    <div class="content">
    <table class="table">
        <thead>
          <tr>
            <th>Existing Courses</th>
          </tr>
        </thead>

        <tbody>
          {% if course_list %}
            {% for course in course_list %}
              <tr >
                <td><a href="{% url 'course:detail' course_name=course.course_name %}">{{ course.course_name }}</a></td>
              </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td>No course, sign up for a new course!</td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>

  </section>
{% endblock %}

course/templates/course/course_list.html
{% extends 'schedule/layout.html' %}



{% block content %}


<div class="bg2"></div>

  <section>
    <div class="container-fluid p-3 bg-dark bg-gradient text-white text-center">
      <h1>Courses</h1>
    </div>

    <div class="content">

      <table class="table">
        <thead>
          <tr>
            <th>Enrolled Courses
              <a href="{% url 'course:form' %}" class="btn btn-primary"><i class="bi bi-plus-square"></i> Add a new course </a>
            </th>
          </tr>
        </thead>
        <tbody>
          {% if course_list %}
            {% for course in course_list %}
              <tr >
                <td><a href="{% url 'course:detail' course_name=course.course_name %}">{{ course.course_name }}</a></td>
              </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td>No course, sign up for a new course!</td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>

  </section>


{% endblock %}