course/urls.py
from django.urls import path
from .views import CourseListView, CourseFormView, CourseDetailView, DocumentFormView
from . import views
app_name = 'course'
urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('form/', CourseFormView.as_view(), name='form'),
    # path('notes/', views.UploadDocumentFormView, name='upload'),
    path('<str:course_name>/', CourseDetailView.as_view(), name='detail'),
    path('<str:course_name>/notes/', views.DocumentFormView, name='upload'), # goes to the file list for class
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name="schedule/home.html")),

    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),

    path('course/', include('course.urls')),
    path('schedule/', include('schedule.urls')),

] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # need this line to go to media for files

schedule/urls.py
from django.urls import path

from . import views
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from django.conf import settings

from django.conf.urls import url
from django.urls import re_path

app_name = 'schedule'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('assignment/form/', views.assignment_form, name='assignment_form'),
    path('assignment/list/', views.AssignmentListView.as_view(), name='assignment_list'),
    path('assignment/create', views.create_assignment, name='create_assignment'),
    path('assignment/delete/<int:assignment_id>', views.delete_assignment, name='delete_assignment'),
    path('calendar/', views.CalendarRedirect, name='calendar1'),

    #path('calendar/', views.redirect_calendar, name='calendar'),

    #maybe write as regular def?
    # path to calendar takes in year and month
    path('calendar/<int:year>/<int:month>/', views.CalendarView, name='calendar'),
    #re_path(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),

]

course/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_out
from django.contrib import messages
import os


class Course(models.Model):
    course_name = models.CharField(max_length=200, default="class")
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.course_name

def upload_path(instance, filename) :
    # dynamically create an upload path used in AWS S3
    return instance.course.course_name + '/ ' + filename

class Document(models.Model):
    # dynamically change upload path
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    docfile = models.FileField(upload_to=upload_path)

    def filename(self): # remove a full path from the filename
        return os.path.basename(self.docfile.name)
    def __str__(self): # use the formatted pathname for its string representation
        return self.filename()

# when a user logs out, display a confirmation message
def logout_task(sender, user, request, **kwargs):
    messages.add_message(
        request,
        messages.INFO,
        f"You are successfully logged out.",
    )
user_logged_out.connect(logout_task)

schedule/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from course.models import Course

class Assignment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # instead of User, Student later?
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True) # changed to match with courses
    title = models.CharField(max_length=200, default="assignment name")
    description = models.CharField(max_length=200, default="description")
    date_created = models.DateTimeField('date created', default=timezone.now)
    due_date = models.DateTimeField('due date', default=timezone.now)

    def __str__(self):
        return self.title

course/forms.py
from django import forms
from .models import Document

class CourseForm(forms.Form):
    course_name = forms.CharField(max_length=200)

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['docfile']

course/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .forms import CourseForm, DocumentForm
from .models import Course, Document

from schedule.models import Assignment
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch') # have to do this for classes
class CourseListView(generic.ListView):
    template_name = 'course/course_list.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        user_info = self.request.user
        cur_user = User.objects.get(username=user_info.username, email=user_info.email)
        return cur_user.course_set.all()

@method_decorator(login_required, name='dispatch') # have to do this for classes
class CourseDetailView(generic.DetailView):
    model = Course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c = get_object_or_404(Course, course_name=self.kwargs.get("course_name"))
        context['documents'] = c.document_set.all()
        context['assignments'] = Assignment.objects.filter(user_id=self.request.user.id).filter(course=c)
        return context

    def get_object(self, queryset=None):
        return get_object_or_404(Course, course_name=self.kwargs.get("course_name"))


@method_decorator(login_required, name='dispatch') # have to do this for classes
class CourseFormView(generic.FormView):
    template_name = 'course/course_form.html'
    form_class = CourseForm

    def get_context_data(self, **kwargs):
        user_info = self.request.user
        cur_user = User.objects.get(username=user_info.username, email=user_info.email)
        all_current_courses = Course.objects.all()
        context = super().get_context_data(**kwargs)
        context['course_list'] = all_current_courses
        return context

    def form_valid(self, form):
        user_info = self.request.user
        course_name = form.cleaned_data.get('course_name').upper()
        cur_user = User.objects.get(username=user_info.username, email=user_info.email)

        course, created = Course.objects.get_or_create(course_name=course_name)
        course.users.add(cur_user)
        return HttpResponseRedirect(reverse('course:list'))


@login_required
def DocumentFormView(request, course_name):
    message = 'Upload Notes!'
    course = Course.objects.get(course_name=course_name)
    if request.method == 'POST': # if the request is POST
        form = DocumentForm(request.POST, request.FILES) # creates a document
        if form.is_valid():
            doc = form.save(commit=False)
            doc.course = course
            doc.save()
            return HttpResponseRedirect(reverse('course:detail', kwargs={'course_name': course_name}))
        else:
            message = 'invalid form:'
    else:
        form = DocumentForm()  # A empty, unbound form, if they don't post

    # Render list page with the documents and the form
    context = {'course_name': course_name, 'form': form, 'message': message}
    return render(request, 'course/course_document_form.html', context)

schedule/views.py
"""
/*

*  REFERENCES
*  Title: <HOW TO CREATE A CALENDAR USING DJANGO>
*  Author: <Hui Wen>
*  Date: <11/17/2021>
*  Code version: <N/A>
*  URL: <https://www.huiwenteo.com/normal/2018/07/24/django-calendar.html>
*  Software License: <N/A>
*

*/

"""


from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Assignment
from course.models import Course
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


from datetime import datetime, timedelta, date
from django.utils.safestring import mark_safe
from .utils import Calendar
import calendar


# from here to the #----------- line referenced Hui Wen's calendar creation tutorial
# calendar creation view
@login_required # requires login before viewing
def CalendarView(request, year, month):

    # filter assignments by users
    assignments = Assignment.objects.filter(user_id=request.user.id)
    # use today's date for the calendar
    #d = get_date(request.GET.get('day', None))
    # Instantiate our calendar class with today's year and date
    cal = Calendar(year, month)
    # Call the formatmonth method, which returns our calendar as a table
    html_cal = cal.formatmonth(assignments, withyear=True) # pass list of assignments in

    #get month
    d = get_date(year, month)
    # prev_month =

    return render(request, 'schedule/calendar.html',
                  {'calendar': mark_safe(html_cal), 'prev_month': prev_month(d), 'next_month': next_month(d)})


# this is just for when user clicks on calendar button on navbar
@login_required # requires login before viewing
def CalendarRedirect(request):
    d = datetime.today()
    return redirect(str(d.year) + '/' + str(d.month)+ '/')

# gets the date based on year and month and formats it
def get_date(year, month):
    if year and month:
        return date(year, month, day=1)
    return datetime.today()

# gets the previous month,
def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = (prev_month.year, prev_month.month)
    return month

# returns next month and the year it comes with
def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = (next_month.year, next_month.month)
    return month

#------------------------------------------------------------------------------------------------------


@login_required # requires login before viewing
def index(request):
    return render(request, 'schedule/index.html')

@method_decorator(login_required, name='dispatch') # have to do this for classes
class IndexView(generic.ListView):
    template_name = 'schedule/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Assignment.objects.filter(user_id=self.request.user.id).order_by('-due_date').reverse()[:5]

@login_required # requires login before viewing
def assignment_form(request): # make sure it's linked with users
    return render(request, 'schedule/assignment_form.html',
    {'course_list': Course.objects.filter(users=request.user).values().order_by('course_name')})
    # filters by users and orders by course name


@method_decorator(login_required, name='dispatch') # have to do this for classes
class AssignmentListView(generic.ListView):
    template_name = 'schedule/assignment_list.html'
    context_object_name = 'assignment_list'
    def get_queryset(self):
        order = self.request.GET.get('sort', 'due_date')
        if(order == 'course'):
            return Assignment.objects.filter(user_id=self.request.user.id).order_by('course__course_name')
        return list(Assignment.objects.filter(user_id=self.request.user.id).order_by(order))

@login_required # requires login before viewing
def create_assignment(request):
    if (request.method == 'POST'):
        course = Course.objects.get(course_name=request.POST["course"])
        title = request.POST["title"]
        desc = request.POST["desc"]
        due_date = request.POST["due_date"]
        if (not course or not title or not desc or not due_date):
            return render(request, 'schedule/assignment_form.html', {
                'error_message': "Please fill out the text boxes.",
                'course_list': Course.objects.filter(users=request.user).values().order_by('course_name')
            })
        if (len(title) > 200):
            return render(request, 'schedule/assignment_form.html', {
                'error_message2': "Assignment title too long",
            })
        Assignment.objects.create( # when assignment is created,
            user_id = request.user.id, # user id associated with this assignment is set to current user
            course = course,
            title = title,
            description = desc,
            date_created = timezone.now(),
            due_date = due_date
        )
    return HttpResponseRedirect(reverse('schedule:assignment_list'))

@login_required # requires login before viewing
def delete_assignment(request, assignment_id):
    assignment = get_object_or_404(Assignment, pk=assignment_id)
    assignment.delete()
    return HttpResponseRedirect(reverse('schedule:assignment_list'))

schedule/templates/schedule/assignment_form.html
{% extends 'schedule/layout.html' %}
{% block content %}


<div class="bg"></div>
<div class="content">
  <section>
    <div class="container-fluid p-3 bg-dark text-white text-center">
      <h1>Create Assignment</h1>
      <p>fill in the text boxes and click submit to set an assignment</p>
    </div>
    <form action="{% url 'schedule:create_assignment'%}" method="post" class="mt-4">
      {% csrf_token %}
      {{ form.as_p }}
      <fieldset> 
        {% if error_message %}
          <div class="alert alert-danger">
            <strong>Warning!</strong> Please fill out the text boxes.
          </div>
        {% endif %}

        {% if error_message2 %}
          <div class="alert alert-danger">
            <strong>Warning!</strong> Assignment title too long.
          </div>
        {% endif %}

        <label for="course">Select a course: </label>
        <select id="course" name="course" class="form-select" aria-label=".form-select-sm example" style="width:auto;" >
          {% for course in course_list %}
            <option value="{{ course.course_name }}" data-type="{{ course.course_name }}">{{ course.course_name }}</option>
          {% endfor %}
        </select>


        <label for="title">Assignment Title: </label>
        <input id="title" type="text" name="title" maxlength="200"><br><br>
        <label for="desc">Description: </label>
        <input id="desc" type="text" name="desc" size="50" maxlength="2000">
        <label for="due_date">Due Date: </label>
        <input id="due_date" type="date" name="due_date">
      </fieldset>
      <div>
        <button type="submit" class="btn btn-primary text-white" >
          Submit
        </button>
      </div>
    </form>
  </section>
</div>
{% endblock %}

schedule/templates/schedule/assignment_list.html
{% extends 'schedule/layout.html' %}
<!-- Page for assignment lists, maybe add a sort feature later on-->


{% block content %}
<div class="bg"></div>
<div class="content">
  <section>
    <div class="container-fluid p-3 bg-dark bg-gradient text-white text-center">
      <h1>Assignments</h1>
      <p>These are all your assignments</p>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Course</th>
          <th>Title</th>
          <th>Description</th>
          <th>Date Created</th>
          <th>Due Date</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% if assignment_list %}
          {% for item in assignment_list %}
          
            <tr>
              
              <td>{{ item.course }}</td>
              <td>{{ item.title }}</td>
              <td>{{ item.description }}</td>
              <td>{{ item.date_created }}</td>
              <td>{{ item.due_date }}</td>
              <td><a href="{% url 'schedule:delete_assignment' item.id %}">delete</a></td>
              <!--
              <td>

                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                  <label class="form-check-label" for="flexCheckDefault">
                    Delete
                  </label>
                </div>
              </td> yeah no this is too difficult-->
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td>No assignments.</td>
          </tr>
          
        {% endif %}
        
        <a href="{% url 'schedule:assignment_form' %}" class='btn ca'><i class="bi bi-journal-plus"></i> Create a new assignment</a>
        <a href="{% url 'schedule:assignment_list' %}?sort=due_date" class='btn dd' style=''> Sort by Due Date</a>
        <a href="{% url 'schedule:assignment_list' %}?sort=date_created" class='btn dc' style=''> Sort by Date Created</a>
        <a href="{% url 'schedule:assignment_list' %}?sort=description" class='btn ds' style=''> Sort by Description</a>
        <a href="{% url 'schedule:assignment_list' %}?sort=title" class='btn st' style=''> Sort by Title</a>
        <a href="{% url 'schedule:assignment_list' %}?sort=course" class='btn sc' style=''> Sort by Course</a>

      </tbody>
    </table>
  </section>
</div>

{% endblock %}

schedule/templates/schedule/calendar.html
{% extends 'schedule/layout.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'schedule/calendar_style.css' %}">
<div class="clearfix">
	<!-- Buttons go to next month, takes in year param and month param-->
	<a class="btn btn-info left" href="{% url 'schedule:calendar' prev_month.0 prev_month.1 %}"> <i class="bi bi-arrow-left"></i> Previous Month</a>
	<a class="btn btn-info right" href="{% url 'schedule:calendar' next_month.0 next_month.1 %}"> Next Month <i class="bi bi-arrow-right"></i></a>
</div>
<div class="bg"></div>

{{ calendar }}

<!--
<div class="modal fade" id="calendarModal" tabindex="-1" aria-labelledby="calendarModalLabel" aria-hidden="true">
<div class="modal-dialog">
  <div class="modal-content">
	<div class="modal-header">
	  <h5 class="modal-title" id="exampleModalLabel">{{ a.title }}</h5>
	  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	</div>
	<div class="modal-body">
	  poop
	</div>
  </div>
</div>
</div> trying to make it show the assignment as a modal but can't cuase im dumb-->
{% endblock %}

schedule/templates/schedule/course_detail.html
{% extends 'schedule/layout.html' %}

{% block content %}
  <section>
    <div class="container-fluid p-3 bg-dark text-white text-center">
      <h1>Students in {{ course.course_name }}</h1>
    </div>
    {% if course %}
      <ul class="mt-3 text-center">
        {% for user in course.users.all %}
          <li>{{ user.username }}</li>
        {% endfor %}
      </ul>
    {% else %}
      <p>no user signed up for this course</p>
    {% endif %}
    <a href="{% url 'course_list' %}">return to list</a>
  </section>
{% endblock %}

schedule/templates/schedule/course_form.html
{% extends 'schedule/layout.html' %}

{% block content %}
  <section>
    <div class="container-fluid p-3 bg-dark text-white text-center">
      <h1>Create Assignment</h1>
      <p>fill in the text boxes and click submit to set an assignment</p>
    </div>
    <form action="{% url 'course_form' %}" method="post" class="mt-3 text-center">
      {% csrf_token %}
      {{ form.as_p }}
      {% comment %}
        }{% if error_message %}
          }  <div class="alert alert-danger">
            }    <strong>Warning!</strong> Please fill out the course name.
            }  </div>
        }{% endif %}
      {% endcomment %}
      {% comment %}
        }<fieldset>
          }  {% if error_message %}
            }    <div class="alert alert-danger">
              }      <strong>Warning!</strong> Please fill out the text boxes.
              }    </div>
          }  {% endif %}
          }  <label for="course">Course: </label>
          }  <input id="course" type="text" name="course" maxlength="200"><br><br>
          }</fieldset>
      {% endcomment %}
      <button type="submit" class="btn btn-primary text-white" >
        Submit
      </button>
    </form>
  </section>
{% endblock %}

schedule/templates/schedule/course_list.html
{% extends 'schedule/layout.html' %}

{% block content %}
  <section>
    <div class="container-fluid p-3 bg-dark text-white text-center">
      <h1>Courses</h1>
    </div>
    <table class="table mt-3">
      <thead>
        <tr>
          <th>Course Name</th>
        </tr>
      </thead>
      <tbody>
        {% if course_list %}
          {% for course in course_list %}
            <tr >
              <td><a href="{% url 'course_detail' pk=course.pk %}">{{ course.course_name }}</a></td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td>No course, sign up for a new course!</td>
          </tr>
        {% endif %}
        <a href="{% url 'course_form' %}">Add a new course</a>
      </tbody>
    </table>
  </section>
{% endblock %}

schedule/templates/schedule/home.html
{% extends "schedule/layout.html" %}
{% block content %}
{% load static %}
{% load socialaccount %}
<!--
*  REFERENCES
*  Title: <Sliding Diagonals Background Effect>
*  Author: <Chris Smith>
*  Date: <11/15/2021>
*  Code version: <N/A>
*  URL: <https://codepen.io/chris22smith/pen/RZogMa>
*  Software License: <N/A>
*
-->


<link rel="stylesheet" type="text/css" href="{% static 'schedule/home_style.css' %}">

    <div class="container-fluid p-3 bg-dark bg-gradient text-white text-center">
      <h1></h1>
    </div>
    <div class="bg"></div>
    <div class="bg bg2"></div>
    <div class="bg bg3"></div>
    <div class="content">
    <h1>Cavalier Calendar</h1>
        <div>
        <p>Organization, the Cavalier way</p>
        <a class="btn button btn-info {% if '/account' in request.path %} active {% endif %}" href="{% provider_login_url 'google' %}"><i class="bi bi-google"></i> Login With Google </a>
        </div>
    </div>

{% endblock %}

schedule/templates/schedule/index.html
{% extends "schedule/layout.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'schedule/base.css' %}">

<div class="bg"></div>
<div class="content">
    <section>
        <div class="container-fluid p-3 bg-dark bg-gradient text-white text-center">
            <h1>Welcome {{ user.username }}</h1>
            <p>Here is your organizer, feel free to use it for your assignments as well as other events!</p>
        </div>
    </section>

    <section>
        <h5> These are your next 5 assignments due! </h5>
        <table class="table">
            <thead>
              <tr>
                <th>Course</th>
                <th>Title</th>
                <th>Due Date</th>
              </tr>
            </thead>
            <tbody>
                <tr>
                {% for assignment in latest_question_list %}
                  <td>{{ assignment.course }} </td>
                  <td>{{ assignment.title }}</td>
                  <td>{{ assignment.due_date}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
</div>




{% endblock %}

schedule/templates/schedule/layout.html
<!--
/*

*  REFERENCES
*  Title: <Modal>
*  Author: <Bootstrap Team>
*  Date: <11/23/2021>
*  Code version: <Bootstrapv5.0>
*  URL: <https://getbootstrap.com/docs/5.0/components/modal/>
*  Software License: <MIT license>
*

*/

-->




<html lang="en">
  <head>
    <title>Your Workspace</title>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="A-22">
    <meta name="description" content="Personal assignment and note organizer">
    <meta name="keywords" content="organizer">

    {% load static %}
    {% load django_bootstrap5 %}
    {% load socialaccount %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'schedule/base.css' %}">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'schedule:index' %}" style="color:Green"><i class="bi bi-journal-text"></i> Organizer </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarItems" aria-controls="navbarItems" aria-expanded="false" aria-label="Navigation Toggler" >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarItems">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/' %} active {% endif %}" aria-current="page" href="{% url 'schedule:index' %}">
                  Home
                </a>
              </li>

              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link {% if '/course' in request.path %} active {% endif %}"
                     href="{% url 'course:list' %}">
                    Course
                  </a>
                </li>

                <li class="nav-item">
                  <a class="nav-link {% if '/assignment' in request.path %} active {% endif %}"
                     href="{% url 'schedule:assignment_list' %}">
                    Assignment
                  </a>
                </li>


                <li class="nav-item">
                  <a class="nav-link"
                     href="{% url 'schedule:calendar1' %}">
                    Calendar
                  </a>
                </li>

                <!--<li class="nav-item">
                  <a class="nav-link navbar-right"
                     href="{% url 'logout' %}">
                    Logout
                  </a>
                </li> -->

                <li class="nav-item">
                   <a href="#" class="nav-link navbar-right" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Logout
                  </a>
                </li>


              {% else %}
                <li class="nav-item">
                  <a class="nav-link {% if '/account' in request.path %} active {% endif %}"
                     href="{% provider_login_url 'google' %}">
                    Login
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <!-- Modal
      I referenced the Bootstrap modal tutorial for this Modal
      -->

      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to log out?</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Confirm by clicking yes
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <a href="{% url 'logout' %}">
                <button type="button" class="btn btn-primary">Yes</button>
              </a>
            </div>
          </div>
        </div>
      </div>

    </header>


    {% block content %}
    {% load static %}

    {% endblock %}
    <div>
      <footer class="page-footer font-small blue text-center">
      <p>Copyright &copy; 2021 A-22</p>
      </footer>
    </div>

  </body>
</html>